name: Security Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  pull-requests: write
  issues: write
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for scanning

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          extra_args: --only-verified

      - name: Debug Gitleaks License
        run: |
          echo "🔍 Checking Gitleaks license configuration..."
          echo "GITLEAKS_LICENSE is set: ${{ secrets.GITLEAKS_LICENSE != '' }}"
          echo "License length: ${#GITLEAKS_LICENSE}"
          echo "First 5 chars: ${GITLEAKS_LICENSE:0:5}..."

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_REPORT_FORMAT: json
          GITLEAKS_REPORT_PATH: gitleaks-report.json

      - name: Check for .env files
        run: |
          echo "🔍 Scanning for .env files..."
          if find . -name ".env*" -type f | grep -q .; then
            echo "❌ Found .env files:"
            find . -name ".env*" -type f
            exit 1
          else
            echo "✅ No .env files found"
          fi

      - name: Check for GitHub tokens
        run: |
          echo "🔍 Scanning for GitHub tokens..."
          if grep -r -i --exclude-dir={node_modules,.git,dist,build} --exclude="*.md" "ghp_[a-zA-Z0-9]{36}" . | grep -q .; then
            echo "❌ Found potential GitHub tokens:"
            grep -r -i --exclude-dir={node_modules,.git,dist,build} --exclude="*.md" "ghp_[a-zA-Z0-9]{36}" . || true
            exit 1
          else
            echo "✅ No GitHub tokens found"
          fi

      - name: Check for npm tokens
        run: |
          echo "🔍 Scanning for npm tokens..."
          if grep -r -i --exclude-dir={node_modules,.git,dist,build} --exclude="*.md" "npm_[a-zA-Z0-9]{36}" . | grep -q .; then
            echo "❌ Found potential npm tokens:"
            grep -r -i --exclude-dir={node_modules,.git,dist,build} --exclude="*.md" "npm_[a-zA-Z0-9]{36}" . || true
            exit 1
          else
            echo "✅ No npm tokens found"
          fi

      - name: Check for private keys
        run: |
          echo "🔍 Scanning for private keys..."
          if grep -r -i --exclude-dir={node_modules,.git,dist,build} --exclude="*.md" "-----BEGIN PRIVATE KEY-----" . | grep -q .; then
            echo "❌ Found potential private keys:"
            grep -r -i --exclude-dir={node_modules,.git,dist,build} --exclude="*.md" "-----BEGIN PRIVATE KEY-----" . || true
            exit 1
          else
            echo "✅ No private keys found"
          fi

      - name: Upload Gitleaks results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          retention-days: 30
